### ISSUE TITLE
Homepage triggers download

### ISSUE THREAD

**Issue by jacebrowning** [Ross-Hunter/nbp-site#2]
Every time I visit the homepage, it's starts fetching the stream for each episode. Is this intentional?

**Comment by Ross-Hunter** [comment]
Hmm, that is the default behavior, but I know how to disable it by hiding the stream on the home page.

**Comment by jacebrowning** [comment]
Perhaps the play button should only be shown after navigating to a specific episode?

**Comment by jacebrowning** [comment]
It looks good now.
